spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: erudio
      port: '27018'
      #port: '27017'
      host: localhost
      auto-index-creation: true
springdoc:
      pathsToMatch: /api/**/v1/**
      swagger-ui:
        use-root-path: true
