cors:
  originPatterns: "http://localhost:8080,http://localhost:3000"
security:
    jwt:
      token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: erudio
      port: '27018'
      #port: '27017'
      host: localhost
      auto-index-creation: true
springdoc:
      pathsToMatch:
        - /auth/**
        - /api/**/v1/**
      swagger-ui:
        use-root-path: true
